os: osx
osx_image: xcode10.2

language: bash

git:
 depth: false
before_cache:
 _brew cleanup
 
cache:
 _ directories:
  _ $HOME/Library/Caches/Homebrew
before_install:
 - whoami
 - echo "start of pipeline"
 - HOMEBREW_NO_AUTO_UPDATE=1
script:
  - ls
  - chmod +x hello.sh
  - ./hello.sh
after_script:
   - echo "end of pipeline"
