os: osx
osx_image: xcode10.2

language: bash

befor_install:
 - whoami
 - echo"start of pipeline"
 - HOMEBREW_ND_AUTO_UPDATE=1
 
 script:
  - ls
  - chmod +x hello.sh
  - ./hello.sh
  
  after_script:
   - echo "end of pipeline"
